---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
  - debug: 
      msg: "Now installing on RedHat"
  - name: Installing apache on redhat server
    yum:
     name: httpd
     state: latest
    when: ansible_os_family == "RedHat"
  - name: Copying os html file
    copy:
     src: ./redhat.html
     dest: /var/www/html/index.html
     mode: 770
    when: ansible_os_family == "RedHat"
  - name: Starting service
    service:
     name: httpd
     state: started
     enabled: yes
    when: ansible_os_family == "RedHat"   
  - debug: 
      msg: "Now installing on ubuntu"
  - name: Installing apache on ubuntu server
    apt:
     name: apache2
     update_cache: yes
     state: present
    when: ansible_os_family == "Ubuntu"
  - name: Copying os html file
    copy:
     src: ./ubuntu.html
     dest: /var/www/html/index.html
     mode: 770
    when: ansible_os_family == "Ubuntu"
  - name: Starting service
    service:
     name: apache2
     state: started
     enabled: yes
    when: ansible_os_family == "Ubuntu"   